```{r}
numSum <- function(featureSet) {
	featureSet %>% 
		group_by(label) %>%
		summarise_each(funs(min(.), max(.), mean(.), median(.), sd(.)), 
					   matches("mean|age|weig|sapsi|sofa"))
}

catSum <- function(featureSet, cat) {
	return(featureSet %>% group_by_(cat, "label") %>% 
		   	summarise(count=n()) %>% ungroup %>% 
		   	group_by_("label") %>% mutate(perc=count/sum(count)))
}

loopDescrPlot <- function(df) {
	ggplot(df, aes_string(colnames(df)[1], "perc")) +
		geom_point(aes(color=as.factor(label), size=perc)) +
		ylab("Percent") + 
		xlab("Trait") + 
		coord_cartesian(xlim=c(0, 1)) +
		ggtitle(colnames(df)[1]) +
		scale_color_manual(values = c("red", "blue")) +
		theme_bw() +
		coord_flip()
}

catVars <- as.list(colnames(features)[c(2, 5:14)])
catStats <- lapply(catVars, catSum, featureSet=features)
catPlots <- lapply(catStats[c(1:7, 10:11)], loopDescrPlot)
catPlots

numSum(features)
numSum(featuresHD)
```

# Center and Scale

```{r}
centerScale <- function(dtm) {
	toScale <- dtm %>% dplyr::select(., matches("mean|weig|sapsi|sofa")) %>% scale()
	dtm %<>% dplyr::select(., -matches("mean|age|weig|sapsi|sofa")) %>% 
		cbind(., toScale)
	return(dtm)
}

features %<>% centerScale
```

# Training and Testing Sets

```{r}
createTrainTest <- function(featureSet) {
	trainIndex <- createDataPartition(featureSet$label, times=1, p=0.7, list=FALSE)
	return(list(featureSet[trainIndex, ], featureSet[-trainIndex, ]))
}

# training [[1]], testing [[2]]
trainTest <- features %>% createTrainTest
```

# Model Creation

```{r}
createModels <- function(trainSet) {
	nlpLogModel <- glm(label ~ ., family=binomial, data=trainSet)
	nlpNaiveBayes <- naiveBayes(as.factor(label) ~ ., data=trainSet, laplace=0)
	nlpInfoModel <- rpart(label ~ ., trainSet, method="class", 
						  parms=list(split="information"))
	nlpGiniModel <- rpart(label ~ ., trainSet, method="class", 
						  parms=list(split="gini"))
	nlpRandomForest <- randomForest(label ~ ., trainSet)
	return(list(nlpLogModel, nlpNaiveBayes, nlpInfoModel, nlpGiniModel))
}
```

# Cross Validation

```{r}
crossValidate <- function(trainSet) {
	tc <- trainControl("cv", 10, savePred=TRUE, classProbs=TRUE, summaryFunction=twoClassSummary)
# 					   classProbs=TRUE, summaryFunction=twoClassSummary)  
	
	logModel <- train(label ~ ., data=trainSet, trControl=tc,  
						 method="glm", metric="ROC")  
	
	nbGrid <- expand.grid(.fL=0, .usekernel=F)
	naiveBayes <- train(label ~ ., data=trainSet, trControl=tc, 
						method="nb", tuneGrid=nbGrid, metric="ROC")  
	
	infoGrid <- expand.grid(.C=0.25)
	infoModel <- train(label ~ ., data=trainSet, trControl=tc,
					   method="J48", tuneGrid=infoGrid, metric="ROC") 
	
	rpartGrid <- expand.grid(.cp=0.2)
	giniModel <- train(label ~ ., data=trainSet, trControl=tc, 
					   method="rpart", tuneGrid=rpartGrid, metric="ROC") 
	
	rfGrid <- expand.grid(.mtry=c(1, 9))
	rfModel <- train(label ~ ., data=trainSet, trControl=tc,
					 method="rf", tuneGrid=rfGrid, metric="ROC")
	
	return(list(logModel, infoModel, giniModel, rfModel))
}

test <- crossValidate(trainTest[[1]])
```

# Test Predictions

```{r}
testResults <- function(models, test, label) {
	
	logitPred <- predict(models[[1]], test, link="class") %>% as.data.frame 
	logitPred <- ifelse(logitPred>0, 1, 0) %>% as.numeric
	logitConMat <- table(logitPred, label) %>% reportStat
	
	nbPred <- predict(models[[2]], test, type="raw") %>% 
		as.data.frame %>% mutate(predLabel=ifelse(`0`>`1`, 0, 1)) %>% 
		dplyr::select(predLabel) %>% unlist %>% as.numeric
	nbConMat <- table(nbPred, label) %>% reportStat
	
	treeInfoPred <- predict(models[[3]], test, link="class") %>% 
		as.data.frame %>% mutate(predLabel=ifelse(`0`>`1`, 0, 1)) %>% 
		dplyr::select(predLabel) %>% unlist %>% as.numeric
	treeInfoConMat <- table(treeInfoPred, label) %>% reportStat
	
	treeGiniPred <- predict(models[[4]], test, link="class") %>% 
		as.data.frame %>% mutate(predLabel=ifelse(`0`>`1`, 0, 1)) %>% 
		dplyr::select(predLabel) %>% unlist %>% as.numeric
	treeGiniConMat <- table(treeGiniPred, label) %>% reportStat
	return(list(logistic=logitConMat, naiveBayes=nbConMat, 
				infoTree=treeInfoConMat, giniTree=treeGiniConMat))
}
```