---
title: "Predicting Sepsis in the ICU"
author: "Ryan Quan (rcq2102)"
date: "April 30, 2015"
output: html_document
---

# Load Data

## Connect to Database

```{r}
# devtools::add_path('~/usr/local/bin/psql')
# devtools::install("~/Downloads/rpostgresql-read-only/RPostgreSQL/")
library(plyr)
library(dplyr)
library(reshape2)
library(magrittr)
db <- src_postgres(dbname = "MIMIC2",
                  host = "ec2-54-163-173-71.compute-1.amazonaws.com",
                  port = 5432,
                  user = "ec2-user",
                  password = "thisisalongpassword1234")
```


## Picking Cases and Controls

### Filtering for First Day ICU Only

```{r, cache=TRUE}
query <- sql(
"SELECT subject_id, hadm_id, icustay_id
FROM mimic2v26.icustay_detail
WHERE (icustay_first_flg = 'Y' AND subject_icustay_seq = '1' AND icustay_age_group = 'adult')
AND subject_id IN
    (SELECT DISTINCT subject_id
    FROM mimic2v26.icd9
    WHERE (code LIKE '995.9%' OR code = '785.52'))"
)
caseID <- tbl(db, query) %>%
    collect()
```

```{r, cache=TRUE}
query <- sql(
"SELECT subject_id, hadm_id, icustay_id
FROM mimic2v26.icustay_detail
WHERE (icustay_first_flg = 'Y' AND subject_icustay_seq = '1' AND icustay_age_group = 'adult')"
)
controlID <- tbl(db, query) %>%
    filter(!(subject_id %in% caseID$subject_id)) %>%
    collect()

```

## Create ID Table

```{r}
set.seed(1)
randomSubset <- sample(controlID$subject_id, 5000)
controls <- controlID[controlID$subject_id %in% randomSubset, ]
ids <- rbind(caseID, controls)
```

## Microbiology Events

```{r}
# q <- sql(
# "SELECT *
# FROM mimic2v26.microbiologyevents
# LIMIT 500"
# )
# shit <- tbl(db, q)
```

## Demographic

```{r}
query <- sql(
"SELECT subject_id, hadm_id, marital_status_descr, overall_payor_group_descr, 
        religion_descr, admission_type_descr, admission_source_descr
FROM mimic2v26.demographic_detail"
)
demographic <- tbl(db, query)
```

```{r}
demographic %<>% 
    filter(subject_id %in% ids$subject_id & hadm_id %in% ids$hadm_id) %>%
    collect()
```
